apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672       # Porta AMQP
      targetPort: 5672
      nodePort: 31672  # Porta externa para AMQP
    - protocol: TCP
      port: 15672      # Porta Painel Web
      targetPort: 15672
      nodePort: 31673  # Porta externa para Painel
  type: NodePort       # Ou LoadBalancer, dependendo do ambiente